name: SoulWell
main: SoulWell\ZulfahmiFjr\Main
author: 
- ZulfahmiFjr
- Convert to pm5 by Mrchlldev
version: 1.5+dev
api: 5.0.0

commands:
 soulwell:
     description: SoulWell plugin
     permission: soulwell.command
 addwell:
     description: Add SoulWell block
     permission: soulwell.command
 addsouls:
     description: Add Soul Keys player
     permission: soulwell.command

permissions:
  soulwell.command:
    default: true
